sonar.organization=usdot-jpo-ode
sonar.projectKey=usdot-jpo-ode_asn1-codec
sonar.projectName=asn1-codec
sonar.projectVersion=1.0

sonar.sources=src,kafka-test/src,include
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.coverageReportPaths=coverage/coverage.xml

sonar.exclusions=**/*.java,pugixml/tests/data/**
sonar.coverage.exclusions=**/*.java
sonar.scm.disabled=true
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8