; Supervisor config file.
;
; For more information on the config file, please see:
; http://supervisord.org/configuration.html

[unix_http_server]
file=/build/supervisor.sock     ; the path to the socket file

[supervisord]
logfile=/build/supervisord.log  ; main log file; default $CWD/supervisord.log
logfile_maxbytes=10MB           ; max main logfile bytes b4 rotation; default 50MB
logfile_backups=2               ; # of main logfile backups; 0 means none, default 10
loglevel=info                   ; log level; default info; others: debug,warn,trace
pidfile=/build/supervisord.pid  ; supervisord pidfile; default supervisord.pid
nodaemon=true                   ; start in foreground if true; default false
silent=false                    ; no logs to stdout if true; default false
minfds=256                      ; min. avail startup file descriptors; default 1024
minprocs=20                     ; min. avail process descriptors;default 200
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///build/supervisor.sock ; use a unix:// URL  for a unix socket

[program:asn1codec]
command=/build/acm -c /asn1_codec/config/%(ENV_ACM_CONFIG_FILE)s -b %(ENV_DOCKER_HOST_IP)s:9092 -v %(ENV_ACM_LOG_LEVEL)s -i /build/logs/log_%(process_num)s.info -R
process_name=%(program_name)s_%(process_num)s
directory=/build
numprocs=%(ENV_ACM_NUMBER_OF_PROCESSES)s
autostart=true
autorestart=true