ASN_SCHEMAS= 1609dot2-P2P.asn 1609dot2-base-types.asn 1609dot2-schema.asn component-cert-management-errors.asn crl-base-types.asn crl-protocol.asn crl-ssp.asn eca-ee-errors.asn la-ma-errors.asn la-pca-errors.asn la-ra-errors.asn ma-pca-errors.asn ma-ra-errors.asn pca-ra-errors.asn ra-pg-errors.asn scms-common-errors.asn scms-error.asn wsa-ssp.asn scms-base-types.asn scms-protocol.asn
ASN_MODULE_SOURCES=	\
	Ieee1609dot2Peer2PeerPDU.c	\
	CaCertP2pPDU.c	\
	Uint3.c	\
	Uint8.c	\
	Uint16.c	\
	Uint32.c	\
	Uint64.c	\
	SequenceOfUint8.c	\
	SequenceOfUint16.c	\
	Opaque.c	\
	HashedId10.c	\
	HashedId8.c	\
	HashedId3.c	\
	SequenceOfHashedId3.c	\
	Time32.c	\
	Time64.c	\
	ValidityPeriod.c	\
	Duration.c	\
	GeographicRegion.c	\
	CircularRegion.c	\
	RectangularRegion.c	\
	SequenceOfRectangularRegion.c	\
	PolygonalRegion.c	\
	TwoDLocation.c	\
	IdentifiedRegion.c	\
	SequenceOfIdentifiedRegion.c	\
	CountryOnly.c	\
	CountryAndRegions.c	\
	CountryAndSubregions.c	\
	RegionAndSubregions.c	\
	SequenceOfRegionAndSubregions.c	\
	ThreeDLocation.c	\
	Latitude.c	\
	Longitude.c	\
	Elevation.c	\
	NinetyDegreeInt.c	\
	KnownLatitude.c	\
	UnknownLatitude.c	\
	OneEightyDegreeInt.c	\
	KnownLongitude.c	\
	UnknownLongitude.c	\
	ElevInt.c	\
	Signature.c	\
	EcdsaP256Signature.c	\
	EcdsaP384Signature.c	\
	EccP256CurvePoint.c	\
	EccP384CurvePoint.c	\
	SymmAlgorithm.c	\
	HashAlgorithm.c	\
	EciesP256EncryptedKey.c	\
	EncryptionKey.c	\
	PublicEncryptionKey.c	\
	BasePublicEncryptionKey.c	\
	PublicVerificationKey.c	\
	SymmetricEncryptionKey.c	\
	PsidSsp.c	\
	SequenceOfPsidSsp.c	\
	Psid.c	\
	SequenceOfPsid.c	\
	ServiceSpecificPermissions.c	\
	BitmapSsp.c	\
	PsidSspRange.c	\
	SequenceOfPsidSspRange.c	\
	SspRange.c	\
	BitmapSspRange.c	\
	SequenceOfOctetString.c	\
	SubjectAssurance.c	\
	CrlSeries.c	\
	IValue.c	\
	Hostname.c	\
	LinkageValue.c	\
	GroupLinkageValue.c	\
	LaId.c	\
	LinkageSeed.c	\
	SignedDataPayload.c	\
	Ieee1609Dot2Data.c	\
	Ieee1609Dot2Content.c	\
	SignedData.c	\
	SignerIdentifier.c	\
	ToBeSignedData.c	\
	HashedData.c	\
	HeaderInfo.c	\
	MissingCrlIdentifier.c	\
	Countersignature.c	\
	EncryptedData.c	\
	RecipientInfo.c	\
	SequenceOfRecipientInfo.c	\
	PreSharedKeyRecipientInfo.c	\
	SymmRecipientInfo.c	\
	PKRecipientInfo.c	\
	EncryptedDataEncryptionKey.c	\
	SymmetricCiphertext.c	\
	AesCcmCiphertext.c	\
	Certificate.c	\
	SequenceOfCertificate.c	\
	CertificateBase.c	\
	CertificateType.c	\
	ImplicitCertificate.c	\
	ExplicitCertificate.c	\
	IssuerIdentifier.c	\
	ToBeSignedCertificate.c	\
	CertificateId.c	\
	LinkageData.c	\
	EndEntityType.c	\
	PsidGroupPermissions.c	\
	SequenceOfPsidGroupPermissions.c	\
	SubjectPermissions.c	\
	VerificationKeyIndicator.c	\
	ComponentCertificateManagementError.c	\
	CrlContents.c	\
	CrlPriorityInfo.c	\
	ToBeSignedHashIdCrl.c	\
	HashBasedRevocationInfo.c	\
	SequenceOfHashBasedRevocationInfo.c	\
	ToBeSignedLinkageValueCrl.c	\
	JMaxGroup.c	\
	SequenceOfJMaxGroup.c	\
	LAGroup.c	\
	SequenceOfLAGroup.c	\
	IMaxGroup.c	\
	SequenceOfIMaxGroup.c	\
	IndividualRevocation.c	\
	SequenceOfIndividualRevocation.c	\
	GroupCrlEntry.c	\
	SequenceOfGroupCrlEntry.c	\
	CrlPsid.c	\
	SecuredCrl.c	\
	CrlSsp.c	\
	CracaType.c	\
	PermissibleCrls.c	\
	EcaEndEntityError.c	\
	LaMaError.c	\
	LaMaBaseErrorCode.c	\
	LaMaLinkageInfoErrorCode.c	\
	LaMaLinkageSeedErrorCode.c	\
	LaPcaError.c	\
	LaPcaErrorCode.c	\
	LaRaError.c	\
	LaRaErrorCode.c	\
	MaPcaError.c	\
	MaPcaErrorCode.c	\
	MaRaError.c	\
	MaRaBaseErrorCode.c	\
	MaRaBlacklistErrorCode.c	\
	MaRaLCIErrorCode.c	\
	MaRaCDVErrorCode.c	\
	PcaRaError.c	\
	PcaRaBaseErrorCode.c	\
	PcaRaRequestErrorCode.c	\
	RaPgError.c	\
	ScmsCommonError.c	\
	ScmsError.c	\
	ScopedComponentCertificateManagementError.c	\
	ScopedEcaEndEntityError.c	\
	ScopedLaMaError.c	\
	ScopedLaMaLIError.c	\
	ScopedLaMaLSError.c	\
	ScopedLaPcaError.c	\
	ScopedLaRaError.c	\
	ScopedMaPcaError.c	\
	ScopedMaRaError.c	\
	ScopedMaRaBlacklistError.c	\
	ScopedMaRaLCIError.c	\
	ScopedPcaRaError.c	\
	WsaSsp.c	\
	AdvertiserPermissions.c	\
	ChannelIdentifier.c	\
	ProviderPermissions.c	\
	ChannelSpecificProviderPermission.c	\
	EdcaIdentifier.c	\
	EnumeratedEdcaIdentifier.c	\
	ExplicitEdcaIdentifier.c	\
	SequenceOfEdcaIdentifier.c

ASN_MODULE_HEADERS=	\
	Ieee1609dot2Peer2PeerPDU.h	\
	CaCertP2pPDU.h	\
	Uint3.h	\
	Uint8.h	\
	Uint16.h	\
	Uint32.h	\
	Uint64.h	\
	SequenceOfUint8.h	\
	SequenceOfUint16.h	\
	Opaque.h	\
	HashedId10.h	\
	HashedId8.h	\
	HashedId3.h	\
	SequenceOfHashedId3.h	\
	Time32.h	\
	Time64.h	\
	ValidityPeriod.h	\
	Duration.h	\
	GeographicRegion.h	\
	CircularRegion.h	\
	RectangularRegion.h	\
	SequenceOfRectangularRegion.h	\
	PolygonalRegion.h	\
	TwoDLocation.h	\
	IdentifiedRegion.h	\
	SequenceOfIdentifiedRegion.h	\
	CountryOnly.h	\
	CountryAndRegions.h	\
	CountryAndSubregions.h	\
	RegionAndSubregions.h	\
	SequenceOfRegionAndSubregions.h	\
	ThreeDLocation.h	\
	Latitude.h	\
	Longitude.h	\
	Elevation.h	\
	NinetyDegreeInt.h	\
	KnownLatitude.h	\
	UnknownLatitude.h	\
	OneEightyDegreeInt.h	\
	KnownLongitude.h	\
	UnknownLongitude.h	\
	ElevInt.h	\
	Signature.h	\
	EcdsaP256Signature.h	\
	EcdsaP384Signature.h	\
	EccP256CurvePoint.h	\
	EccP384CurvePoint.h	\
	SymmAlgorithm.h	\
	HashAlgorithm.h	\
	EciesP256EncryptedKey.h	\
	EncryptionKey.h	\
	PublicEncryptionKey.h	\
	BasePublicEncryptionKey.h	\
	PublicVerificationKey.h	\
	SymmetricEncryptionKey.h	\
	PsidSsp.h	\
	SequenceOfPsidSsp.h	\
	Psid.h	\
	SequenceOfPsid.h	\
	ServiceSpecificPermissions.h	\
	BitmapSsp.h	\
	PsidSspRange.h	\
	SequenceOfPsidSspRange.h	\
	SspRange.h	\
	BitmapSspRange.h	\
	SequenceOfOctetString.h	\
	SubjectAssurance.h	\
	CrlSeries.h	\
	IValue.h	\
	Hostname.h	\
	LinkageValue.h	\
	GroupLinkageValue.h	\
	LaId.h	\
	LinkageSeed.h	\
	SignedDataPayload.h	\
	Ieee1609Dot2Data.h	\
	Ieee1609Dot2Content.h	\
	SignedData.h	\
	SignerIdentifier.h	\
	ToBeSignedData.h	\
	HashedData.h	\
	HeaderInfo.h	\
	MissingCrlIdentifier.h	\
	Countersignature.h	\
	EncryptedData.h	\
	RecipientInfo.h	\
	SequenceOfRecipientInfo.h	\
	PreSharedKeyRecipientInfo.h	\
	SymmRecipientInfo.h	\
	PKRecipientInfo.h	\
	EncryptedDataEncryptionKey.h	\
	SymmetricCiphertext.h	\
	AesCcmCiphertext.h	\
	Certificate.h	\
	SequenceOfCertificate.h	\
	CertificateBase.h	\
	CertificateType.h	\
	ImplicitCertificate.h	\
	ExplicitCertificate.h	\
	IssuerIdentifier.h	\
	ToBeSignedCertificate.h	\
	CertificateId.h	\
	LinkageData.h	\
	EndEntityType.h	\
	PsidGroupPermissions.h	\
	SequenceOfPsidGroupPermissions.h	\
	SubjectPermissions.h	\
	VerificationKeyIndicator.h	\
	ComponentCertificateManagementError.h	\
	CrlContents.h	\
	CrlPriorityInfo.h	\
	ToBeSignedHashIdCrl.h	\
	HashBasedRevocationInfo.h	\
	SequenceOfHashBasedRevocationInfo.h	\
	ToBeSignedLinkageValueCrl.h	\
	JMaxGroup.h	\
	SequenceOfJMaxGroup.h	\
	LAGroup.h	\
	SequenceOfLAGroup.h	\
	IMaxGroup.h	\
	SequenceOfIMaxGroup.h	\
	IndividualRevocation.h	\
	SequenceOfIndividualRevocation.h	\
	GroupCrlEntry.h	\
	SequenceOfGroupCrlEntry.h	\
	CrlPsid.h	\
	SecuredCrl.h	\
	CrlSsp.h	\
	CracaType.h	\
	PermissibleCrls.h	\
	EcaEndEntityError.h	\
	LaMaError.h	\
	LaMaBaseErrorCode.h	\
	LaMaLinkageInfoErrorCode.h	\
	LaMaLinkageSeedErrorCode.h	\
	LaPcaError.h	\
	LaPcaErrorCode.h	\
	LaRaError.h	\
	LaRaErrorCode.h	\
	MaPcaError.h	\
	MaPcaErrorCode.h	\
	MaRaError.h	\
	MaRaBaseErrorCode.h	\
	MaRaBlacklistErrorCode.h	\
	MaRaLCIErrorCode.h	\
	MaRaCDVErrorCode.h	\
	PcaRaError.h	\
	PcaRaBaseErrorCode.h	\
	PcaRaRequestErrorCode.h	\
	RaPgError.h	\
	ScmsCommonError.h	\
	ScmsError.h	\
	ScopedComponentCertificateManagementError.h	\
	ScopedEcaEndEntityError.h	\
	ScopedLaMaError.h	\
	ScopedLaMaLIError.h	\
	ScopedLaMaLSError.h	\
	ScopedLaPcaError.h	\
	ScopedLaRaError.h	\
	ScopedMaPcaError.h	\
	ScopedMaRaError.h	\
	ScopedMaRaBlacklistError.h	\
	ScopedMaRaLCIError.h	\
	ScopedPcaRaError.h	\
	WsaSsp.h	\
	AdvertiserPermissions.h	\
	ChannelIdentifier.h	\
	ProviderPermissions.h	\
	ChannelSpecificProviderPermission.h	\
	EdcaIdentifier.h	\
	EnumeratedEdcaIdentifier.h	\
	ExplicitEdcaIdentifier.h	\
	SequenceOfEdcaIdentifier.h

ASN_MODULE_HEADERS+=OPEN_TYPE.h
ASN_MODULE_SOURCES+=OPEN_TYPE.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_HEADERS+=UTF8String.h
ASN_MODULE_HEADERS+=BOOLEAN.h
ASN_MODULE_SOURCES+=BOOLEAN.c
ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_HEADERS+=NativeEnumerated.h
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NULL.h
ASN_MODULE_SOURCES+=NULL.c
ASN_MODULE_SOURCES+=NativeEnumerated.c
ASN_MODULE_HEADERS+=NativeInteger.h
ASN_MODULE_SOURCES+=NativeInteger.c
ASN_MODULE_SOURCES+=UTF8String.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_ioc.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=asn_bit_data.h
ASN_MODULE_SOURCES+=asn_bit_data.c
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c
ASN_MODULE_HEADERS+=per_support.h
ASN_MODULE_SOURCES+=per_support.c
ASN_MODULE_HEADERS+=per_decoder.h
ASN_MODULE_SOURCES+=per_decoder.c
ASN_MODULE_HEADERS+=per_encoder.h
ASN_MODULE_SOURCES+=per_encoder.c
ASN_MODULE_HEADERS+=per_opentype.h
ASN_MODULE_SOURCES+=per_opentype.c
ASN_CONVERTER_SOURCES+=converter-sample.c
ASN_MODULE_HEADERS+=oer_decoder.h
ASN_MODULE_SOURCES+=oer_decoder.c
ASN_MODULE_HEADERS+=oer_encoder.h
ASN_MODULE_SOURCES+=oer_encoder.c
ASN_MODULE_HEADERS+=oer_support.h
ASN_MODULE_SOURCES+=oer_support.c
ASN_MODULE_SOURCES+=OPEN_TYPE_oer.c
ASN_MODULE_SOURCES+=INTEGER_oer.c
ASN_MODULE_SOURCES+=OCTET_STRING_oer.c
ASN_MODULE_SOURCES+=NativeInteger_oer.c
ASN_MODULE_SOURCES+=NativeEnumerated_oer.c
ASN_MODULE_SOURCES+=constr_SEQUENCE_oer.c
ASN_MODULE_SOURCES+=constr_CHOICE_oer.c
ASN_MODULE_SOURCES+=constr_SET_OF_oer.c
ASN_MODULE_SOURCES+=BIT_STRING_oer.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = scms-dump
CPPFLAGS += -DASN_CONVERTER_TITLE="SCMS decoder" -DASN_DISABLE_PER_SUPPORT -DPDU=Ieee1609Dot2Data -I.
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: Ieee1609Dot2Data.c $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source: $(ASN_SCHEMAS)
	asn1c -pdu=Ieee1609Dot2Data -fcompound-names -gen-OER -gen-PER $(ASN_SCHEMAS)

Ieee1609Dot2Data.c: $(ASN_SCHEMAS)
	make regen
	@touch Ieee1609Dot2Data.c
	make
	

distclean: clean
	rm -f $(ASN_MODULE_SOURCES)
	rm -f $(ASN_MODULE_HEADERS)
	rm -f $(ASN_CONVERTER_SOURCES) $(ASN_CONVERTER_HEADERS)
	rm -f Makefile.am.sample
