/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "./j2735-asn-files/2024/ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_AbsolutePosition2d_H_
#define	_AbsolutePosition2d_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EfcDataDictionary_Longitude.h"
#include "EfcDataDictionary_Latitude.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AbsolutePosition2d */
typedef struct AbsolutePosition2d {
	EfcDataDictionary_Longitude_t	 gnssLon;
	EfcDataDictionary_Latitude_t	 gnssLat;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AbsolutePosition2d_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AbsolutePosition2d;

#ifdef __cplusplus
}
#endif

#endif	/* _AbsolutePosition2d_H_ */
#include "asn_internal.h"
