/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_AdvisorySituationBundle_H_
#define	_AdvisorySituationBundle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "TemporaryID.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AdvisoryBroadcast;

/* AdvisorySituationBundle */
typedef struct AdvisorySituationBundle {
	long	 bundleNumber;
	TemporaryID_t	 bundleId;
	struct AdvisorySituationBundle__asdRecords {
		A_SEQUENCE_OF(struct AdvisoryBroadcast) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} asdRecords;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisorySituationBundle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisorySituationBundle;
extern asn_SEQUENCE_specifics_t asn_SPC_AdvisorySituationBundle_specs_1;
extern asn_TYPE_member_t asn_MBR_AdvisorySituationBundle_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AdvisoryBroadcast.h"

#endif	/* _AdvisorySituationBundle_H_ */
#include "asn_internal.h"
