/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_AdvisoryBroadcastType_H_
#define	_AdvisoryBroadcastType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdvisoryBroadcastType {
	AdvisoryBroadcastType_spatAggregate	= 0,
	AdvisoryBroadcastType_map	= 1,
	AdvisoryBroadcastType_tim	= 2,
	AdvisoryBroadcastType_ev	= 3
	/*
	 * Enumeration is extensible
	 */
} e_AdvisoryBroadcastType;

/* AdvisoryBroadcastType */
typedef long	 AdvisoryBroadcastType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdvisoryBroadcastType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdvisoryBroadcastType;
extern const asn_INTEGER_specifics_t asn_SPC_AdvisoryBroadcastType_specs_1;
asn_struct_free_f AdvisoryBroadcastType_free;
asn_struct_print_f AdvisoryBroadcastType_print;
asn_constr_check_f AdvisoryBroadcastType_constraint;
ber_type_decoder_f AdvisoryBroadcastType_decode_ber;
der_type_encoder_f AdvisoryBroadcastType_encode_der;
xer_type_decoder_f AdvisoryBroadcastType_decode_xer;
xer_type_encoder_f AdvisoryBroadcastType_encode_xer;
oer_type_decoder_f AdvisoryBroadcastType_decode_oer;
oer_type_encoder_f AdvisoryBroadcastType_encode_oer;
per_type_decoder_f AdvisoryBroadcastType_decode_uper;
per_type_encoder_f AdvisoryBroadcastType_encode_uper;
per_type_decoder_f AdvisoryBroadcastType_decode_aper;
per_type_encoder_f AdvisoryBroadcastType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisoryBroadcastType_H_ */
#include "asn_internal.h"
