/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_AdvisorySituationData_H_
#define	_AdvisorySituationData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiDialogID.h"
#include "SemiSequenceID.h"
#include "GroupID.h"
#include "TemporaryID.h"
#include "TimeToLive.h"
#include "GeoRegion.h"
#include "AdvisoryDetails.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AdvisorySituationData */
typedef struct AdvisorySituationData {
	SemiDialogID_t	 dialogID;
	SemiSequenceID_t	 seqID;
	GroupID_t	 groupID;
	TemporaryID_t	 requestID;
	TemporaryID_t	*recordID;	/* OPTIONAL */
	TimeToLive_t	*timeToLive;	/* OPTIONAL */
	GeoRegion_t	 serviceRegion;
	AdvisoryDetails_t	 asdmDetails;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisorySituationData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisorySituationData;

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisorySituationData_H_ */
#include "asn_internal.h"
