/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_AdvisoryDetails_H_
#define	_AdvisoryDetails_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TemporaryID.h"
#include "AdvisoryBroadcastType.h"
#include "DistributionType.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DFullTime;

/* AdvisoryDetails */
typedef struct AdvisoryDetails {
	TemporaryID_t	 asdmID;
	AdvisoryBroadcastType_t	 asdmType;
	DistributionType_t	 distType;
	struct DFullTime	*startTime;	/* OPTIONAL */
	struct DFullTime	*stopTime;	/* OPTIONAL */
	OCTET_STRING_t	 advisoryMessage;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisoryDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisoryDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_AdvisoryDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_AdvisoryDetails_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DFullTime.h"

#endif	/* _AdvisoryDetails_H_ */
#include "asn_internal.h"
