/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "./j2735-asn-files/2024/ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_AxlesWeightLimits_H_
#define	_AxlesWeightLimits_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AxleWeightLimit;

/* AxlesWeightLimits */
typedef struct AxlesWeightLimits {
	A_SEQUENCE_OF(struct AxleWeightLimit) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AxlesWeightLimits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AxlesWeightLimits;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AxleWeightLimit.h"

#endif	/* _AxlesWeightLimits_H_ */
#include "asn_internal.h"
