/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataConfig"
 * 	found in "./j2735-asn-files/2024/J2945-C-ProbeDataConfig-2024-rel-v1.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_CfgEvents_H_
#define	_CfgEvents_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CfgEvents */
typedef struct CfgEvents {
	BOOLEAN_t	*absActivated;	/* OPTIONAL */
	BOOLEAN_t	*tractionCtlLoss;	/* OPTIONAL */
	BOOLEAN_t	*stabilityCtlActivated;	/* OPTIONAL */
	BOOLEAN_t	*hardBraking;	/* OPTIONAL */
	long	*swerveThreshold;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CfgEvents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CfgEvents;
extern asn_SEQUENCE_specifics_t asn_SPC_CfgEvents_specs_1;
extern asn_TYPE_member_t asn_MBR_CfgEvents_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CfgEvents_H_ */
#include "asn_internal.h"
