/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataConfig"
 * 	found in "./j2735-asn-files/2024/J2945-C-ProbeDataConfig-2024-rel-v1.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_CfgTrafficSigEncounters_H_
#define	_CfgTrafficSigEncounters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "BOOLEAN.h"
#include "IntersectionID.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CfgTrafficSigEncounters */
typedef struct CfgTrafficSigEncounters {
	struct CfgTrafficSigEncounters__intersections {
		A_SEQUENCE_OF(IntersectionID_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *intersections;
	long	*trfcsigApproachDelay;	/* OPTIONAL */
	long	*trfsigApproachSpeed;	/* OPTIONAL */
	BOOLEAN_t	*trfsigArrivalGreen;	/* OPTIONAL */
	BOOLEAN_t	*trfsigArrivalRed;	/* OPTIONAL */
	long	*trfsigPedDelay;	/* OPTIONAL */
	BOOLEAN_t	*trfsigSpatMismatch;	/* OPTIONAL */
	BOOLEAN_t	*trfsigSpatTimingError;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CfgTrafficSigEncounters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CfgTrafficSigEncounters;
extern asn_SEQUENCE_specifics_t asn_SPC_CfgTrafficSigEncounters_specs_1;
extern asn_TYPE_member_t asn_MBR_CfgTrafficSigEncounters_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _CfgTrafficSigEncounters_H_ */
#include "asn_internal.h"
