/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_CountryOnly_H_
#define	_CountryOnly_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UnCountryId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CountryOnly */
typedef UnCountryId_t	 CountryOnly_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CountryOnly;
asn_struct_free_f CountryOnly_free;
asn_struct_print_f CountryOnly_print;
asn_constr_check_f CountryOnly_constraint;
ber_type_decoder_f CountryOnly_decode_ber;
der_type_encoder_f CountryOnly_encode_der;
xer_type_decoder_f CountryOnly_decode_xer;
xer_type_encoder_f CountryOnly_encode_xer;
oer_type_decoder_f CountryOnly_decode_oer;
oer_type_encoder_f CountryOnly_encode_oer;
per_type_decoder_f CountryOnly_decode_uper;
per_type_encoder_f CountryOnly_encode_uper;
per_type_decoder_f CountryOnly_decode_aper;
per_type_encoder_f CountryOnly_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CountryOnly_H_ */
#include "asn_internal.h"
