/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_CrlContents_H_
#define	_CrlContents_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "CrlSeries.h"
#include "HashedId8.h"
#include "Time32.h"
#include "CrlPriorityInfo.h"
#include "TypeSpecificCrlContents.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CrlContents */
typedef struct CrlContents {
	Uint8_t	 version;
	CrlSeries_t	 crlSeries;
	HashedId8_t	 crlCraca;
	Time32_t	 issueDate;
	Time32_t	 nextCrl;
	CrlPriorityInfo_t	 priorityInfo;
	TypeSpecificCrlContents_t	 typeSpecific;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CrlContents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlContents;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlContents_H_ */
#include "asn_internal.h"
