/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_DataSubscriptionRequest_H_
#define	_DataSubscriptionRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiDialogID.h"
#include "SemiSequenceID.h"
#include "GroupID.h"
#include "TemporaryID.h"
#include "DFullTime.h"
#include "VsmType.h"
#include "IsdType.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataSubscriptionRequest__type_PR {
	DataSubscriptionRequest__type_PR_NOTHING,	/* No components present */
	DataSubscriptionRequest__type_PR_vsmType,
	DataSubscriptionRequest__type_PR_isdType
} DataSubscriptionRequest__type_PR;

/* Forward declarations */
struct GeoRegion;

/* DataSubscriptionRequest */
typedef struct DataSubscriptionRequest {
	SemiDialogID_t	 dialogID;
	SemiSequenceID_t	 seqID;
	GroupID_t	 groupID;
	TemporaryID_t	 requestID;
	struct DataSubscriptionRequest__type {
		DataSubscriptionRequest__type_PR present;
		union DataSubscriptionRequest__type_u {
			VsmType_t	 vsmType;
			IsdType_t	 isdType;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} type;
	DFullTime_t	 endTime;
	struct GeoRegion	*serviceRegion;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataSubscriptionRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataSubscriptionRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeoRegion.h"

#endif	/* _DataSubscriptionRequest_H_ */
#include "asn_internal.h"
