/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_DsrcInstructions_H_
#define	_DsrcInstructions_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TxMode.h"
#include "TxChannel.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DsrcInstructions */
typedef struct DsrcInstructions {
	TxMode_t	 biTxMode;
	TxChannel_t	 biTxChannel;
	long	 biTxInterval;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DsrcInstructions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DsrcInstructions;
extern asn_SEQUENCE_specifics_t asn_SPC_DsrcInstructions_specs_1;
extern asn_TYPE_member_t asn_MBR_DsrcInstructions_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DsrcInstructions_H_ */
#include "asn_internal.h"
