/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "./j2735-asn-files/2024/J2735-Common-2024-rel-v1.1.2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_DYearMonth_H_
#define	_DYearMonth_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DYear.h"
#include "DMonth.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DYearMonth */
typedef struct DYearMonth {
	DYear_t	 year;
	DMonth_t	 month;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DYearMonth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DYearMonth;

#ifdef __cplusplus
}
#endif

#endif	/* _DYearMonth_H_ */
#include "asn_internal.h"
