/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_EcsigP256Signature_H_
#define	_EcsigP256Signature_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EcsigP256Signature */
typedef struct EcsigP256Signature {
	OCTET_STRING_t	 rSig;
	OCTET_STRING_t	 sSig;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EcsigP256Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EcsigP256Signature;
extern asn_SEQUENCE_specifics_t asn_SPC_EcsigP256Signature_specs_1;
extern asn_TYPE_member_t asn_MBR_EcsigP256Signature_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EcsigP256Signature_H_ */
#include "asn_internal.h"
