/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "./j2735-asn-files/2024/ISO17573-EfcDataDictionary.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_EfcDataDictionary_IssuerIdentifier_H_
#define	_EfcDataDictionary_IssuerIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EfcDataDictionary_IssuerIdentifier */
typedef long	 EfcDataDictionary_IssuerIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EfcDataDictionary_IssuerIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EfcDataDictionary_IssuerIdentifier;
asn_struct_free_f EfcDataDictionary_IssuerIdentifier_free;
asn_struct_print_f EfcDataDictionary_IssuerIdentifier_print;
asn_constr_check_f EfcDataDictionary_IssuerIdentifier_constraint;
ber_type_decoder_f EfcDataDictionary_IssuerIdentifier_decode_ber;
der_type_encoder_f EfcDataDictionary_IssuerIdentifier_encode_der;
xer_type_decoder_f EfcDataDictionary_IssuerIdentifier_decode_xer;
xer_type_encoder_f EfcDataDictionary_IssuerIdentifier_encode_xer;
oer_type_decoder_f EfcDataDictionary_IssuerIdentifier_decode_oer;
oer_type_encoder_f EfcDataDictionary_IssuerIdentifier_encode_oer;
per_type_decoder_f EfcDataDictionary_IssuerIdentifier_decode_uper;
per_type_encoder_f EfcDataDictionary_IssuerIdentifier_encode_uper;
per_type_decoder_f EfcDataDictionary_IssuerIdentifier_decode_aper;
per_type_encoder_f EfcDataDictionary_IssuerIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EfcDataDictionary_IssuerIdentifier_H_ */
#include "asn_internal.h"
