/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_Emissions_H_
#define	_Emissions_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Emissions */
typedef long	 Emissions_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Emissions_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Emissions;
asn_struct_free_f Emissions_free;
asn_struct_print_f Emissions_print;
asn_constr_check_f Emissions_constraint;
ber_type_decoder_f Emissions_decode_ber;
der_type_encoder_f Emissions_encode_der;
xer_type_decoder_f Emissions_decode_xer;
xer_type_encoder_f Emissions_encode_xer;
oer_type_decoder_f Emissions_decode_oer;
oer_type_encoder_f Emissions_encode_oer;
per_type_decoder_f Emissions_decode_uper;
per_type_encoder_f Emissions_encode_uper;
per_type_decoder_f Emissions_decode_aper;
per_type_encoder_f Emissions_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Emissions_H_ */
#include "asn_internal.h"
