/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "./scms-asn-files/EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#include "EtsiTs102941CrlRequest.h"

/*
 * This type is implemented using NULL,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_EtsiTs102941CrlRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (5 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EtsiTs102941CrlRequest = {
	"EtsiTs102941CrlRequest",
	"EtsiTs102941CrlRequest",
	&asn_OP_NULL,
	asn_DEF_EtsiTs102941CrlRequest_tags_1,
	sizeof(asn_DEF_EtsiTs102941CrlRequest_tags_1)
		/sizeof(asn_DEF_EtsiTs102941CrlRequest_tags_1[0]), /* 1 */
	asn_DEF_EtsiTs102941CrlRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_EtsiTs102941CrlRequest_tags_1)
		/sizeof(asn_DEF_EtsiTs102941CrlRequest_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NULL_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

