/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "./scms-asn-files/EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_EtsiTs103097HeaderInfoExtensionId_H_
#define	_EtsiTs103097HeaderInfoExtensionId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ExtId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs103097HeaderInfoExtensionId */
typedef ExtId_t	 EtsiTs103097HeaderInfoExtensionId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EtsiTs103097HeaderInfoExtensionId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs103097HeaderInfoExtensionId;
asn_struct_free_f EtsiTs103097HeaderInfoExtensionId_free;
asn_struct_print_f EtsiTs103097HeaderInfoExtensionId_print;
asn_constr_check_f EtsiTs103097HeaderInfoExtensionId_constraint;
ber_type_decoder_f EtsiTs103097HeaderInfoExtensionId_decode_ber;
der_type_encoder_f EtsiTs103097HeaderInfoExtensionId_encode_der;
xer_type_decoder_f EtsiTs103097HeaderInfoExtensionId_decode_xer;
xer_type_encoder_f EtsiTs103097HeaderInfoExtensionId_encode_xer;
oer_type_decoder_f EtsiTs103097HeaderInfoExtensionId_decode_oer;
oer_type_encoder_f EtsiTs103097HeaderInfoExtensionId_encode_oer;
per_type_decoder_f EtsiTs103097HeaderInfoExtensionId_decode_uper;
per_type_encoder_f EtsiTs103097HeaderInfoExtensionId_encode_uper;
per_type_decoder_f EtsiTs103097HeaderInfoExtensionId_decode_aper;
per_type_encoder_f EtsiTs103097HeaderInfoExtensionId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs103097HeaderInfoExtensionId_H_ */
#include "asn_internal.h"
