/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_ExpansionAlgorithmIdentifier_H_
#define	_ExpansionAlgorithmIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExpansionAlgorithmIdentifier {
	ExpansionAlgorithmIdentifier_sha256ForI_aesForJ	= 0,
	ExpansionAlgorithmIdentifier_sm3ForI_sm4ForJ	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ExpansionAlgorithmIdentifier;

/* ExpansionAlgorithmIdentifier */
typedef long	 ExpansionAlgorithmIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExpansionAlgorithmIdentifier;
asn_struct_free_f ExpansionAlgorithmIdentifier_free;
asn_struct_print_f ExpansionAlgorithmIdentifier_print;
asn_constr_check_f ExpansionAlgorithmIdentifier_constraint;
ber_type_decoder_f ExpansionAlgorithmIdentifier_decode_ber;
der_type_encoder_f ExpansionAlgorithmIdentifier_encode_der;
xer_type_decoder_f ExpansionAlgorithmIdentifier_decode_xer;
xer_type_encoder_f ExpansionAlgorithmIdentifier_encode_xer;
oer_type_decoder_f ExpansionAlgorithmIdentifier_decode_oer;
oer_type_encoder_f ExpansionAlgorithmIdentifier_encode_oer;
per_type_decoder_f ExpansionAlgorithmIdentifier_decode_uper;
per_type_encoder_f ExpansionAlgorithmIdentifier_encode_uper;
per_type_decoder_f ExpansionAlgorithmIdentifier_decode_aper;
per_type_encoder_f ExpansionAlgorithmIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExpansionAlgorithmIdentifier_H_ */
#include "asn_internal.h"
