/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_GeoRegion_H_
#define	_GeoRegion_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Position3D.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GeoRegion */
typedef struct GeoRegion {
	Position3D_t	 nwCorner;
	Position3D_t	 seCorner;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeoRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeoRegion;
extern asn_SEQUENCE_specifics_t asn_SPC_GeoRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_GeoRegion_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GeoRegion_H_ */
#include "asn_internal.h"
