/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "./j2735-asn-files/2024/J2735-Common-2024-rel-v1.1.2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_Gravel_H_
#define	_Gravel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GravelType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Gravel */
typedef struct Gravel {
	GravelType_t	 type;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Gravel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Gravel;
extern asn_SEQUENCE_specifics_t asn_SPC_Gravel_specs_1;
extern asn_TYPE_member_t asn_MBR_Gravel_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Gravel_H_ */
#include "asn_internal.h"
