/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "./j2735-asn-files/2024/J2735-Common-2024-rel-v1.1.2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_IceType_H_
#define	_IceType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IceType {
	IceType_smooth	= 0
	/*
	 * Enumeration is extensible
	 */
} e_IceType;

/* IceType */
typedef long	 IceType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_IceType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IceType;
extern const asn_INTEGER_specifics_t asn_SPC_IceType_specs_1;
asn_struct_free_f IceType_free;
asn_struct_print_f IceType_print;
asn_constr_check_f IceType_constraint;
ber_type_decoder_f IceType_decode_ber;
der_type_encoder_f IceType_encode_der;
xer_type_decoder_f IceType_decode_xer;
xer_type_encoder_f IceType_encode_xer;
oer_type_decoder_f IceType_decode_oer;
oer_type_encoder_f IceType_encode_oer;
per_type_decoder_f IceType_decode_uper;
per_type_encoder_f IceType_encode_uper;
per_type_decoder_f IceType_decode_aper;
per_type_encoder_f IceType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _IceType_H_ */
#include "asn_internal.h"
