/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "./scms-asn-files/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_Ieee1609HeaderInfoExtensionId_H_
#define	_Ieee1609HeaderInfoExtensionId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ExtId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Ieee1609HeaderInfoExtensionId */
typedef ExtId_t	 Ieee1609HeaderInfoExtensionId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ieee1609HeaderInfoExtensionId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609HeaderInfoExtensionId;
asn_struct_free_f Ieee1609HeaderInfoExtensionId_free;
asn_struct_print_f Ieee1609HeaderInfoExtensionId_print;
asn_constr_check_f Ieee1609HeaderInfoExtensionId_constraint;
ber_type_decoder_f Ieee1609HeaderInfoExtensionId_decode_ber;
der_type_encoder_f Ieee1609HeaderInfoExtensionId_encode_der;
xer_type_decoder_f Ieee1609HeaderInfoExtensionId_decode_xer;
xer_type_encoder_f Ieee1609HeaderInfoExtensionId_encode_xer;
oer_type_decoder_f Ieee1609HeaderInfoExtensionId_decode_oer;
oer_type_encoder_f Ieee1609HeaderInfoExtensionId_encode_oer;
per_type_decoder_f Ieee1609HeaderInfoExtensionId_decode_uper;
per_type_encoder_f Ieee1609HeaderInfoExtensionId_encode_uper;
per_type_decoder_f Ieee1609HeaderInfoExtensionId_decode_aper;
per_type_encoder_f Ieee1609HeaderInfoExtensionId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609HeaderInfoExtensionId_H_ */
#include "asn_internal.h"
