/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "./scms-asn-files/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_Ieee1609Dot2_IssuerIdentifier_H_
#define	_Ieee1609Dot2_IssuerIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HashedId8.h"
#include "HashAlgorithm.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ieee1609Dot2_IssuerIdentifier_PR {
	Ieee1609Dot2_IssuerIdentifier_PR_NOTHING,	/* No components present */
	Ieee1609Dot2_IssuerIdentifier_PR_sha256AndDigest,
	Ieee1609Dot2_IssuerIdentifier_PR_self,
	/* Extensions may appear below */
	Ieee1609Dot2_IssuerIdentifier_PR_sha384AndDigest,
	Ieee1609Dot2_IssuerIdentifier_PR_sm3AndDigest
} Ieee1609Dot2_IssuerIdentifier_PR;

/* Ieee1609Dot2_IssuerIdentifier */
typedef struct Ieee1609Dot2_IssuerIdentifier {
	Ieee1609Dot2_IssuerIdentifier_PR present;
	union Ieee1609Dot2_IssuerIdentifier_u {
		HashedId8_t	 sha256AndDigest;
		HashAlgorithm_t	 self;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		HashedId8_t	 sha384AndDigest;
		HashedId8_t	 sm3AndDigest;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ieee1609Dot2_IssuerIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2_IssuerIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_Ieee1609Dot2_IssuerIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_Ieee1609Dot2_IssuerIdentifier_1[4];
extern asn_per_constraints_t asn_PER_type_Ieee1609Dot2_IssuerIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609Dot2_IssuerIdentifier_H_ */
#include "asn_internal.h"
