/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_Ieee1609Dot2BaseTypes_Elevation_H_
#define	_Ieee1609Dot2BaseTypes_Elevation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint16.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Ieee1609Dot2BaseTypes_Elevation */
typedef Uint16_t	 Ieee1609Dot2BaseTypes_Elevation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ieee1609Dot2BaseTypes_Elevation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2BaseTypes_Elevation;
asn_struct_free_f Ieee1609Dot2BaseTypes_Elevation_free;
asn_struct_print_f Ieee1609Dot2BaseTypes_Elevation_print;
asn_constr_check_f Ieee1609Dot2BaseTypes_Elevation_constraint;
ber_type_decoder_f Ieee1609Dot2BaseTypes_Elevation_decode_ber;
der_type_encoder_f Ieee1609Dot2BaseTypes_Elevation_encode_der;
xer_type_decoder_f Ieee1609Dot2BaseTypes_Elevation_decode_xer;
xer_type_encoder_f Ieee1609Dot2BaseTypes_Elevation_encode_xer;
oer_type_decoder_f Ieee1609Dot2BaseTypes_Elevation_decode_oer;
oer_type_encoder_f Ieee1609Dot2BaseTypes_Elevation_encode_oer;
per_type_decoder_f Ieee1609Dot2BaseTypes_Elevation_decode_uper;
per_type_encoder_f Ieee1609Dot2BaseTypes_Elevation_encode_uper;
per_type_decoder_f Ieee1609Dot2BaseTypes_Elevation_decode_aper;
per_type_encoder_f Ieee1609Dot2BaseTypes_Elevation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609Dot2BaseTypes_Elevation_H_ */
#include "asn_internal.h"
