/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ManeuverSharingAndCoordinatingMessage"
 * 	found in "./j2735-asn-files/2024/J3186-ManeuverSharingandCoordinatingMessage-2024-rel-v1.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#include "Maneuver.h"

asn_TYPE_member_t asn_MBR_Maneuver_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Maneuver, subManeuverList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubManeuverList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"subManeuverList"
		},
};
static const ber_tlv_tag_t asn_DEF_Maneuver_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Maneuver_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* subManeuverList */
};
asn_SEQUENCE_specifics_t asn_SPC_Maneuver_specs_1 = {
	sizeof(struct Maneuver),
	offsetof(struct Maneuver, _asn_ctx),
	asn_MAP_Maneuver_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Maneuver = {
	"Maneuver",
	"Maneuver",
	&asn_OP_SEQUENCE,
	asn_DEF_Maneuver_tags_1,
	sizeof(asn_DEF_Maneuver_tags_1)
		/sizeof(asn_DEF_Maneuver_tags_1[0]), /* 1 */
	asn_DEF_Maneuver_tags_1,	/* Same as above */
	sizeof(asn_DEF_Maneuver_tags_1)
		/sizeof(asn_DEF_Maneuver_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Maneuver_1,
	1,	/* Elements count */
	&asn_SPC_Maneuver_specs_1	/* Additional specs */
};

