/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RoadWeatherMessage"
 * 	found in "./j2735-asn-files/2024/J2945-3-RoadWeatherMessage-2024-rel-v2.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_NTCIPEssTemperatureSensorHeight_H_
#define	_NTCIPEssTemperatureSensorHeight_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NTCIPEssTemperatureSensorHeight */
typedef long	 NTCIPEssTemperatureSensorHeight_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NTCIPEssTemperatureSensorHeight_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NTCIPEssTemperatureSensorHeight;
asn_struct_free_f NTCIPEssTemperatureSensorHeight_free;
asn_struct_print_f NTCIPEssTemperatureSensorHeight_print;
asn_constr_check_f NTCIPEssTemperatureSensorHeight_constraint;
ber_type_decoder_f NTCIPEssTemperatureSensorHeight_decode_ber;
der_type_encoder_f NTCIPEssTemperatureSensorHeight_encode_der;
xer_type_decoder_f NTCIPEssTemperatureSensorHeight_decode_xer;
xer_type_encoder_f NTCIPEssTemperatureSensorHeight_encode_xer;
oer_type_decoder_f NTCIPEssTemperatureSensorHeight_decode_oer;
oer_type_encoder_f NTCIPEssTemperatureSensorHeight_encode_oer;
per_type_decoder_f NTCIPEssTemperatureSensorHeight_decode_uper;
per_type_encoder_f NTCIPEssTemperatureSensorHeight_encode_uper;
per_type_decoder_f NTCIPEssTemperatureSensorHeight_decode_aper;
per_type_encoder_f NTCIPEssTemperatureSensorHeight_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NTCIPEssTemperatureSensorHeight_H_ */
#include "asn_internal.h"
