/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_ObjectDiscoveryData_H_
#define	_ObjectDiscoveryData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiDialogID.h"
#include "SemiSequenceID.h"
#include "GroupID.h"
#include "TemporaryID.h"
#include "Count.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceRecord;

/* ObjectDiscoveryData */
typedef struct ObjectDiscoveryData {
	SemiDialogID_t	 dialogID;
	SemiSequenceID_t	 seqID;
	GroupID_t	 groupID;
	TemporaryID_t	 requestID;
	struct ObjectDiscoveryData__serviceInfo {
		Count_t	 countRecords;
		struct ObjectDiscoveryData__serviceInfo__serviceRecords {
			A_SEQUENCE_OF(struct ServiceRecord) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} serviceRecords;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} serviceInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectDiscoveryData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectDiscoveryData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceRecord.h"

#endif	/* _ObjectDiscoveryData_H_ */
#include "asn_internal.h"
