/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "./scms-asn-files/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#include "OperatingOrganizationId.h"

/*
 * This type is implemented using OBJECT_IDENTIFIER,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_OperatingOrganizationId_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (6 << 2))
};
asn_TYPE_descriptor_t asn_DEF_OperatingOrganizationId = {
	"OperatingOrganizationId",
	"OperatingOrganizationId",
	&asn_OP_OBJECT_IDENTIFIER,
	asn_DEF_OperatingOrganizationId_tags_1,
	sizeof(asn_DEF_OperatingOrganizationId_tags_1)
		/sizeof(asn_DEF_OperatingOrganizationId_tags_1[0]), /* 1 */
	asn_DEF_OperatingOrganizationId_tags_1,	/* Same as above */
	sizeof(asn_DEF_OperatingOrganizationId_tags_1)
		/sizeof(asn_DEF_OperatingOrganizationId_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		OBJECT_IDENTIFIER_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

