/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "./scms-asn-files/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_OperatingOrganizationId_H_
#define	_OperatingOrganizationId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OperatingOrganizationId */
typedef OBJECT_IDENTIFIER_t	 OperatingOrganizationId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OperatingOrganizationId;
asn_struct_free_f OperatingOrganizationId_free;
asn_struct_print_f OperatingOrganizationId_print;
asn_constr_check_f OperatingOrganizationId_constraint;
ber_type_decoder_f OperatingOrganizationId_decode_ber;
der_type_encoder_f OperatingOrganizationId_encode_der;
xer_type_decoder_f OperatingOrganizationId_decode_xer;
xer_type_encoder_f OperatingOrganizationId_encode_xer;
oer_type_decoder_f OperatingOrganizationId_decode_oer;
oer_type_encoder_f OperatingOrganizationId_encode_oer;
per_type_decoder_f OperatingOrganizationId_decode_uper;
per_type_encoder_f OperatingOrganizationId_encode_uper;
per_type_decoder_f OperatingOrganizationId_decode_aper;
per_type_encoder_f OperatingOrganizationId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _OperatingOrganizationId_H_ */
#include "asn_internal.h"
