/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "./j2735-asn-files/2024/J2735-Common-2024-rel-v1.1.2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_PathHistoryPointList_H_
#define	_PathHistoryPointList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathHistoryPoint;

/* PathHistoryPointList */
typedef struct PathHistoryPointList {
	A_SEQUENCE_OF(struct PathHistoryPoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathHistoryPointList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathHistoryPointList;
extern asn_SET_OF_specifics_t asn_SPC_PathHistoryPointList_specs_1;
extern asn_TYPE_member_t asn_MBR_PathHistoryPointList_1[1];
extern asn_per_constraints_t asn_PER_type_PathHistoryPointList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PathHistoryPoint.h"

#endif	/* _PathHistoryPointList_H_ */
#include "asn_internal.h"
