/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_PublicVerificationKey_H_
#define	_PublicVerificationKey_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EccP256CurvePoint.h"
#include "EccP384CurvePoint.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PublicVerificationKey_PR {
	PublicVerificationKey_PR_NOTHING,	/* No components present */
	PublicVerificationKey_PR_ecdsaNistP256,
	PublicVerificationKey_PR_ecdsaBrainpoolP256r1,
	/* Extensions may appear below */
	PublicVerificationKey_PR_ecdsaBrainpoolP384r1,
	PublicVerificationKey_PR_ecdsaNistP384,
	PublicVerificationKey_PR_ecsigSm2
} PublicVerificationKey_PR;

/* PublicVerificationKey */
typedef struct PublicVerificationKey {
	PublicVerificationKey_PR present;
	union PublicVerificationKey_u {
		EccP256CurvePoint_t	 ecdsaNistP256;
		EccP256CurvePoint_t	 ecdsaBrainpoolP256r1;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		EccP384CurvePoint_t	 ecdsaBrainpoolP384r1;
		EccP384CurvePoint_t	 ecdsaNistP384;
		EccP256CurvePoint_t	 ecsigSm2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicVerificationKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicVerificationKey;
extern asn_CHOICE_specifics_t asn_SPC_PublicVerificationKey_specs_1;
extern asn_TYPE_member_t asn_MBR_PublicVerificationKey_1[5];
extern asn_per_constraints_t asn_PER_type_PublicVerificationKey_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicVerificationKey_H_ */
#include "asn_internal.h"
