/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ProbeDataReport"
 * 	found in "./j2735-asn-files/2024/J2945-C-ProbeDataReport-2024-rel-v1.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_RptDevType_H_
#define	_RptDevType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RptDevType */
typedef struct RptDevType {
	BOOLEAN_t	 oemOrAftermarket;
	BOOLEAN_t	 canOrIvnConnected;
	BOOLEAN_t	*mcoCapable;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RptDevType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RptDevType;
extern asn_SEQUENCE_specifics_t asn_SPC_RptDevType_specs_1;
extern asn_TYPE_member_t asn_MBR_RptDevType_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RptDevType_H_ */
#include "asn_internal.h"
