/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_SeedEvolutionFunctionIdentifier_H_
#define	_SeedEvolutionFunctionIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SeedEvolutionFunctionIdentifier */
typedef NULL_t	 SeedEvolutionFunctionIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeedEvolutionFunctionIdentifier;
asn_struct_free_f SeedEvolutionFunctionIdentifier_free;
asn_struct_print_f SeedEvolutionFunctionIdentifier_print;
asn_constr_check_f SeedEvolutionFunctionIdentifier_constraint;
ber_type_decoder_f SeedEvolutionFunctionIdentifier_decode_ber;
der_type_encoder_f SeedEvolutionFunctionIdentifier_encode_der;
xer_type_decoder_f SeedEvolutionFunctionIdentifier_decode_xer;
xer_type_encoder_f SeedEvolutionFunctionIdentifier_encode_xer;
oer_type_decoder_f SeedEvolutionFunctionIdentifier_decode_oer;
oer_type_encoder_f SeedEvolutionFunctionIdentifier_encode_oer;
per_type_decoder_f SeedEvolutionFunctionIdentifier_decode_uper;
per_type_encoder_f SeedEvolutionFunctionIdentifier_encode_uper;
per_type_decoder_f SeedEvolutionFunctionIdentifier_decode_aper;
per_type_encoder_f SeedEvolutionFunctionIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SeedEvolutionFunctionIdentifier_H_ */
#include "asn_internal.h"
