/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_SemiSequenceID_H_
#define	_SemiSequenceID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemiSequenceID {
	SemiSequenceID_svcReq	= 1,
	SemiSequenceID_svcResp	= 2,
	SemiSequenceID_dataReq	= 3,
	SemiSequenceID_dataConf	= 4,
	SemiSequenceID_data	= 5,
	SemiSequenceID_accept	= 6,
	SemiSequenceID_receipt	= 7,
	SemiSequenceID_subscriptionReq	= 8,
	SemiSequenceID_subscriptinoResp	= 9,
	SemiSequenceID_subscriptionCancel	= 10
	/*
	 * Enumeration is extensible
	 */
} e_SemiSequenceID;

/* SemiSequenceID */
typedef long	 SemiSequenceID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SemiSequenceID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SemiSequenceID;
extern const asn_INTEGER_specifics_t asn_SPC_SemiSequenceID_specs_1;
asn_struct_free_f SemiSequenceID_free;
asn_struct_print_f SemiSequenceID_print;
asn_constr_check_f SemiSequenceID_constraint;
ber_type_decoder_f SemiSequenceID_decode_ber;
der_type_encoder_f SemiSequenceID_encode_der;
xer_type_decoder_f SemiSequenceID_decode_xer;
xer_type_encoder_f SemiSequenceID_encode_xer;
oer_type_decoder_f SemiSequenceID_decode_oer;
oer_type_encoder_f SemiSequenceID_encode_oer;
per_type_decoder_f SemiSequenceID_decode_uper;
per_type_encoder_f SemiSequenceID_encode_uper;
per_type_decoder_f SemiSequenceID_decode_aper;
per_type_encoder_f SemiSequenceID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SemiSequenceID_H_ */
#include "asn_internal.h"
