/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_SemiDialogID_H_
#define	_SemiDialogID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemiDialogID {
	SemiDialogID_vehSitData	= 154,
	SemiDialogID_dataSubscription	= 155,
	SemiDialogID_advSitDataDep	= 156,
	SemiDialogID_advSitDatDist	= 157,
	SemiDialogID_reserved1	= 158,
	SemiDialogID_reserved2	= 159,
	SemiDialogID_objReg	= 160,
	SemiDialogID_objDisc	= 161,
	SemiDialogID_intersectionSitDataDep	= 162,
	SemiDialogID_intersectionSitDataQuery	= 163
	/*
	 * Enumeration is extensible
	 */
} e_SemiDialogID;

/* SemiDialogID */
typedef long	 SemiDialogID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SemiDialogID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SemiDialogID;
extern const asn_INTEGER_specifics_t asn_SPC_SemiDialogID_specs_1;
asn_struct_free_f SemiDialogID_free;
asn_struct_print_f SemiDialogID_print;
asn_constr_check_f SemiDialogID_constraint;
ber_type_decoder_f SemiDialogID_decode_ber;
der_type_encoder_f SemiDialogID_encode_der;
xer_type_decoder_f SemiDialogID_decode_xer;
xer_type_encoder_f SemiDialogID_encode_xer;
oer_type_decoder_f SemiDialogID_decode_oer;
oer_type_encoder_f SemiDialogID_encode_oer;
per_type_decoder_f SemiDialogID_decode_uper;
per_type_encoder_f SemiDialogID_encode_uper;
per_type_decoder_f SemiDialogID_decode_aper;
per_type_encoder_f SemiDialogID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SemiDialogID_H_ */
#include "asn_internal.h"
