/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_SequenceOfPsid_H_
#define	_SequenceOfPsid_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2BaseTypes_Psid.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfPsid */
typedef struct SequenceOfPsid {
	A_SEQUENCE_OF(Ieee1609Dot2BaseTypes_Psid_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfPsid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfPsid;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfPsid_H_ */
#include "asn_internal.h"
