/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#include "ServiceID.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ServiceID_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ServiceID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ServiceID_value2enum_1[] = {
	{ 1,	3,	"sdc" },
	{ 2,	3,	"sdw" },
	{ 3,	4,	"scms" },
	{ 4,	4,	"ords" },
	{ 5,	5,	"other" }
};
static const unsigned int asn_MAP_ServiceID_enum2value_1[] = {
	3,	/* ords(4) */
	4,	/* other(5) */
	2,	/* scms(3) */
	0,	/* sdc(1) */
	1	/* sdw(2) */
};
const asn_INTEGER_specifics_t asn_SPC_ServiceID_specs_1 = {
	asn_MAP_ServiceID_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ServiceID_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ServiceID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ServiceID = {
	"ServiceID",
	"ServiceID",
	&asn_OP_NativeEnumerated,
	asn_DEF_ServiceID_tags_1,
	sizeof(asn_DEF_ServiceID_tags_1)
		/sizeof(asn_DEF_ServiceID_tags_1[0]), /* 1 */
	asn_DEF_ServiceID_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceID_tags_1)
		/sizeof(asn_DEF_ServiceID_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ServiceID_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ServiceID_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ServiceID_specs_1	/* Additional specs */
};

