/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_ServiceID_H_
#define	_ServiceID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceID {
	ServiceID_sdc	= 1,
	ServiceID_sdw	= 2,
	ServiceID_scms	= 3,
	ServiceID_ords	= 4,
	ServiceID_other	= 5
} e_ServiceID;

/* ServiceID */
typedef long	 ServiceID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ServiceID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ServiceID;
extern const asn_INTEGER_specifics_t asn_SPC_ServiceID_specs_1;
asn_struct_free_f ServiceID_free;
asn_struct_print_f ServiceID_print;
asn_constr_check_f ServiceID_constraint;
ber_type_decoder_f ServiceID_decode_ber;
der_type_encoder_f ServiceID_encode_der;
xer_type_decoder_f ServiceID_decode_xer;
xer_type_encoder_f ServiceID_encode_xer;
oer_type_decoder_f ServiceID_decode_oer;
oer_type_encoder_f ServiceID_encode_oer;
per_type_decoder_f ServiceID_decode_uper;
per_type_encoder_f ServiceID_encode_uper;
per_type_decoder_f ServiceID_decode_aper;
per_type_encoder_f ServiceID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceID_H_ */
#include "asn_internal.h"
