/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TollAdvertisementMessage"
 * 	found in "./j2735-asn-files/2024/J3217-TollAdvertisementMsg-2024-rel-v1.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_SpecialCharges_H_
#define	_SpecialCharges_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EngineCharacteristics.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PaymentFee;
struct OperatorDefined;

/* SpecialCharges */
typedef struct SpecialCharges {
	struct PaymentFee	*hov2Charge;	/* OPTIONAL */
	struct PaymentFee	*hov3Charge;	/* OPTIONAL */
	struct PaymentFee	*hov4Charge;	/* OPTIONAL */
	struct PaymentFee	*hov5PlusCharge;	/* OPTIONAL */
	struct PaymentFee	*cleanAirCharge;	/* OPTIONAL */
	struct OperatorDefined	*operatorDefined;	/* OPTIONAL */
	EngineCharacteristics_t	*engineCharacteristics;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpecialCharges_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpecialCharges;
extern asn_SEQUENCE_specifics_t asn_SPC_SpecialCharges_specs_1;
extern asn_TYPE_member_t asn_MBR_SpecialCharges_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PaymentFee.h"
#include "OperatorDefined.h"

#endif	/* _SpecialCharges_H_ */
#include "asn_internal.h"
