/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_ThreeDLocation_H_
#define	_ThreeDLocation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2BaseTypes_Latitude.h"
#include "Ieee1609Dot2BaseTypes_Longitude.h"
#include "Ieee1609Dot2BaseTypes_Elevation.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ThreeDLocation */
typedef struct ThreeDLocation {
	Ieee1609Dot2BaseTypes_Latitude_t	 latitude;
	Ieee1609Dot2BaseTypes_Longitude_t	 longitude;
	Ieee1609Dot2BaseTypes_Elevation_t	 elevation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ThreeDLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThreeDLocation;
extern asn_SEQUENCE_specifics_t asn_SPC_ThreeDLocation_specs_1;
extern asn_TYPE_member_t asn_MBR_ThreeDLocation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ThreeDLocation_H_ */
#include "asn_internal.h"
