/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "./scms-asn-files/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_ToBeSignedLinkageValueCrlWithAlgIdentifier_H_
#define	_ToBeSignedLinkageValueCrlWithAlgIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IValue.h"
#include "Uint8.h"
#include "SeedEvolutionFunctionIdentifier.h"
#include "LvGenerationFunctionIdentifier.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SequenceOfJMaxGroup;
struct SequenceOfGroupCrlEntry;
struct SequenceOfGroupSingleSeedCrlEntry;

/* ToBeSignedLinkageValueCrlWithAlgIdentifier */
typedef struct ToBeSignedLinkageValueCrlWithAlgIdentifier {
	IValue_t	 iRev;
	Uint8_t	 indexWithinI;
	SeedEvolutionFunctionIdentifier_t	 seedEvolution;
	LvGenerationFunctionIdentifier_t	 lvGeneration;
	struct SequenceOfJMaxGroup	*individual;	/* OPTIONAL */
	struct SequenceOfGroupCrlEntry	*groups;	/* OPTIONAL */
	struct SequenceOfGroupSingleSeedCrlEntry	*groupsSingleSeed;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ToBeSignedLinkageValueCrlWithAlgIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedLinkageValueCrlWithAlgIdentifier;
extern asn_SEQUENCE_specifics_t asn_SPC_ToBeSignedLinkageValueCrlWithAlgIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_ToBeSignedLinkageValueCrlWithAlgIdentifier_1[7];
extern asn_per_constraints_t asn_PER_type_ToBeSignedLinkageValueCrlWithAlgIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SequenceOfJMaxGroup.h"
#include "SequenceOfGroupCrlEntry.h"
#include "SequenceOfGroupSingleSeedCrlEntry.h"

#endif	/* _ToBeSignedLinkageValueCrlWithAlgIdentifier_H_ */
#include "asn_internal.h"
