/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TollAdvertisementMessage"
 * 	found in "./j2735-asn-files/2024/J3217-TollAdvertisementMsg-2024-rel-v1.1.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_TollAdvertisementMessage_H_
#define	_TollAdvertisementMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TollChargesTable.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TollAdvertisementInfo;

/* TollAdvertisementMessage */
typedef struct TollAdvertisementMessage {
	TollChargesTable_t	 tollChargesTable;
	struct TollAdvertisementInfo	*tollAdvInfo;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TollAdvertisementMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TollAdvertisementMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_TollAdvertisementMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_TollAdvertisementMessage_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TollAdvertisementInfo.h"

#endif	/* _TollAdvertisementMessage_H_ */
#include "asn_internal.h"
