/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_TxMode_H_
#define	_TxMode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TxMode {
	TxMode_continuous	= 0,
	TxMode_alternating	= 1
} e_TxMode;

/* TxMode */
typedef long	 TxMode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TxMode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TxMode;
extern const asn_INTEGER_specifics_t asn_SPC_TxMode_specs_1;
asn_struct_free_f TxMode_free;
asn_struct_print_f TxMode_print;
asn_constr_check_f TxMode_constraint;
ber_type_decoder_f TxMode_decode_ber;
der_type_encoder_f TxMode_encode_der;
xer_type_decoder_f TxMode_decode_xer;
xer_type_encoder_f TxMode_encode_xer;
oer_type_decoder_f TxMode_decode_oer;
oer_type_encoder_f TxMode_encode_oer;
per_type_decoder_f TxMode_decode_uper;
per_type_encoder_f TxMode_encode_uper;
per_type_decoder_f TxMode_decode_aper;
per_type_encoder_f TxMode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TxMode_H_ */
#include "asn_internal.h"
