/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_VehicleSituationStatus_H_
#define	_VehicleSituationStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ExteriorLights.h"
#include "ThrottlePosition.h"
#include "TirePressure.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSituationStatus */
typedef struct VehicleSituationStatus {
	ExteriorLights_t	 lights;
	ThrottlePosition_t	*throttlePos;	/* OPTIONAL */
	struct VehicleSituationStatus__tirePressure {
		TirePressure_t	 leftFront;
		TirePressure_t	 leftRear;
		TirePressure_t	 rightFront;
		TirePressure_t	 rightRear;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tirePressure;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSituationStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSituationStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSituationStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSituationStatus_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSituationStatus_H_ */
#include "asn_internal.h"
