/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BasicSafetyMessage"
 * 	found in "./j2735-asn-files/2024/J2735-BasicSafetyMessage-2024-rel-v1.1.2.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_VehicleData_H_
#define	_VehicleData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleHeight.h"
#include "VehicleMass.h"
#include "TrailerWeight.h"
#include "BOOLEAN.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BumperHeights;
struct PivotPointDescription;
struct Axles;

/* VehicleData */
typedef struct VehicleData {
	VehicleHeight_t	*height;	/* OPTIONAL */
	struct BumperHeights	*bumpers;	/* OPTIONAL */
	VehicleMass_t	*mass;	/* OPTIONAL */
	TrailerWeight_t	*doNotUse;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	BOOLEAN_t	*trailerPresent;	/* OPTIONAL */
	struct PivotPointDescription	*pivotPoint;	/* OPTIONAL */
	struct Axles	*axles;	/* OPTIONAL */
	long	*leanAngle;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleData;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleData_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleData_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BumperHeights.h"
#include "PivotPointDescription.h"
#include "Axles.h"

#endif	/* _VehicleData_H_ */
#include "asn_internal.h"
