/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "./semi-asn-files/2024/SEMI_v2.4.1_111524_j2024.asn"
 * 	`asn1c -fcompound-names -gen-OER -fincludes-quoted -no-gen-JER -pdu=all -D ./generated-files/2024`
 */

#ifndef	_VehSitRecord_H_
#define	_VehSitRecord_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TemporaryID.h"
#include "DDateTime.h"
#include "Position3D.h"
#include "FundamentalSituationalStatus.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSituationStatus;
struct Weather;
struct Environmental;
struct ElectricVeh;

/* VehSitRecord */
typedef struct VehSitRecord {
	TemporaryID_t	 tempID;
	DDateTime_t	 time;
	Position3D_t	 pos;
	FundamentalSituationalStatus_t	 fundamental;
	struct VehicleSituationStatus	*vehstat;	/* OPTIONAL */
	struct Weather	*weather;	/* OPTIONAL */
	struct Environmental	*env;	/* OPTIONAL */
	struct ElectricVeh	*elveh;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehSitRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehSitRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_VehSitRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_VehSitRecord_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleSituationStatus.h"
#include "Weather.h"
#include "Environmental.h"
#include "ElectricVeh.h"

#endif	/* _VehSitRecord_H_ */
#include "asn_internal.h"
