/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER`
 */

#include "EcdsaP256Signature.h"

static int
memb_s_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_s_constr_3 GCC_NOTUSED = {
	{ 0, 0 },
	32	/* (SIZE(32..32)) */};
asn_TYPE_member_t asn_MBR_EcdsaP256Signature_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EcdsaP256Signature, r),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EccP256CurvePoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"r"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EcdsaP256Signature, s),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_s_constraint_1,
		&asn_OER_memb_s_constr_3,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"s"
		},
};
static const ber_tlv_tag_t asn_DEF_EcdsaP256Signature_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EcdsaP256Signature_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* s */
};
asn_SEQUENCE_specifics_t asn_SPC_EcdsaP256Signature_specs_1 = {
	sizeof(struct EcdsaP256Signature),
	offsetof(struct EcdsaP256Signature, _asn_ctx),
	asn_MAP_EcdsaP256Signature_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EcdsaP256Signature = {
	"EcdsaP256Signature",
	"EcdsaP256Signature",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EcdsaP256Signature_tags_1,
	sizeof(asn_DEF_EcdsaP256Signature_tags_1)
		/sizeof(asn_DEF_EcdsaP256Signature_tags_1[0]), /* 1 */
	asn_DEF_EcdsaP256Signature_tags_1,	/* Same as above */
	sizeof(asn_DEF_EcdsaP256Signature_tags_1)
		/sizeof(asn_DEF_EcdsaP256Signature_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_EcdsaP256Signature_1,
	2,	/* Elements count */
	&asn_SPC_EcdsaP256Signature_specs_1	/* Additional specs */
};

