/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "1609dot2-schema.asn"
 * 	`asn1c -gen-OER`
 */

#include "HashedData.h"

static int
memb_sha256HashedData_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_sha256HashedData_constr_2 GCC_NOTUSED = {
	{ 0, 0 },
	32	/* (SIZE(32..32)) */};
static asn_oer_constraints_t asn_OER_type_HashedData_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_HashedData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HashedData, choice.sha256HashedData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_sha256HashedData_constraint_1,
		&asn_OER_memb_sha256HashedData_constr_2,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sha256HashedData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_HashedData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* sha256HashedData */
};
asn_CHOICE_specifics_t asn_SPC_HashedData_specs_1 = {
	sizeof(struct HashedData),
	offsetof(struct HashedData, _asn_ctx),
	offsetof(struct HashedData, present),
	sizeof(((struct HashedData *)0)->present),
	asn_MAP_HashedData_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_HashedData = {
	"HashedData",
	"HashedData",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_oer,
	CHOICE_encode_oer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_OER_type_HashedData_constr_1,
	0,	/* No PER visible constraints */
	asn_MBR_HashedData_1,
	1,	/* Elements count */
	&asn_SPC_HashedData_specs_1	/* Additional specs */
};

