/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "1609dot2-schema.asn"
 * 	`asn1c -gen-OER`
 */

#include "HeaderInfo.h"

asn_TYPE_member_t asn_MBR_HeaderInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HeaderInfo, psid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Psid,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"psid"
		},
	{ ATF_POINTER, 6, offsetof(struct HeaderInfo, generationTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time64,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generationTime"
		},
	{ ATF_POINTER, 5, offsetof(struct HeaderInfo, expiryTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time64,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"expiryTime"
		},
	{ ATF_POINTER, 4, offsetof(struct HeaderInfo, generationLocation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ThreeDLocation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generationLocation"
		},
	{ ATF_POINTER, 3, offsetof(struct HeaderInfo, p2pcdLearningRequest),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashedId3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"p2pcdLearningRequest"
		},
	{ ATF_POINTER, 2, offsetof(struct HeaderInfo, missingCrlIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MissingCrlIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"missingCrlIdentifier"
		},
	{ ATF_POINTER, 1, offsetof(struct HeaderInfo, encryptionKey),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EncryptionKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptionKey"
		},
};
static const int asn_MAP_HeaderInfo_oms_1[] = { 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_HeaderInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HeaderInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* psid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* generationTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* expiryTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* generationLocation */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* p2pcdLearningRequest */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* missingCrlIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* encryptionKey */
};
asn_SEQUENCE_specifics_t asn_SPC_HeaderInfo_specs_1 = {
	sizeof(struct HeaderInfo),
	offsetof(struct HeaderInfo, _asn_ctx),
	asn_MAP_HeaderInfo_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_HeaderInfo_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	6,	/* Start extensions */
	8	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_HeaderInfo = {
	"HeaderInfo",
	"HeaderInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_HeaderInfo_tags_1,
	sizeof(asn_DEF_HeaderInfo_tags_1)
		/sizeof(asn_DEF_HeaderInfo_tags_1[0]), /* 1 */
	asn_DEF_HeaderInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_HeaderInfo_tags_1)
		/sizeof(asn_DEF_HeaderInfo_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_HeaderInfo_1,
	7,	/* Elements count */
	&asn_SPC_HeaderInfo_specs_1	/* Additional specs */
};

