/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER`
 */

#ifndef	_Hostname_H_
#define	_Hostname_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Hostname */
typedef UTF8String_t	 Hostname_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Hostname;
asn_struct_free_f Hostname_free;
asn_struct_print_f Hostname_print;
asn_constr_check_f Hostname_constraint;
ber_type_decoder_f Hostname_decode_ber;
der_type_encoder_f Hostname_encode_der;
xer_type_decoder_f Hostname_decode_xer;
xer_type_encoder_f Hostname_encode_xer;
oer_type_decoder_f Hostname_decode_oer;
oer_type_encoder_f Hostname_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Hostname_H_ */
#include <asn_internal.h>
