/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER`
 */

#ifndef	_Psid_H_
#define	_Psid_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Psid */
typedef long	 Psid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Psid;
asn_struct_free_f Psid_free;
asn_struct_print_f Psid_print;
asn_constr_check_f Psid_constraint;
ber_type_decoder_f Psid_decode_ber;
der_type_encoder_f Psid_encode_der;
xer_type_decoder_f Psid_decode_xer;
xer_type_encoder_f Psid_encode_xer;
oer_type_decoder_f Psid_decode_oer;
oer_type_encoder_f Psid_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Psid_H_ */
#include <asn_internal.h>
