/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER`
 */

#include "SequenceOfOctetString.h"

static int
memb_OCTET_STRING_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		(void)st; /* Unused variable */
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_Member_constr_2 GCC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_oer_constraints_t asn_OER_type_SequenceOfOctetString_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
asn_TYPE_member_t asn_MBR_SequenceOfOctetString_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		memb_OCTET_STRING_constraint_1,
		&asn_OER_memb_Member_constr_2,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SequenceOfOctetString_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_SequenceOfOctetString_specs_1 = {
	sizeof(struct SequenceOfOctetString),
	offsetof(struct SequenceOfOctetString, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SequenceOfOctetString = {
	"SequenceOfOctetString",
	"SequenceOfOctetString",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_oer,
	SEQUENCE_OF_encode_oer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SequenceOfOctetString_tags_1,
	sizeof(asn_DEF_SequenceOfOctetString_tags_1)
		/sizeof(asn_DEF_SequenceOfOctetString_tags_1[0]), /* 1 */
	asn_DEF_SequenceOfOctetString_tags_1,	/* Same as above */
	sizeof(asn_DEF_SequenceOfOctetString_tags_1)
		/sizeof(asn_DEF_SequenceOfOctetString_tags_1[0]), /* 1 */
	&asn_OER_type_SequenceOfOctetString_constr_1,
	0,	/* No PER visible constraints */
	asn_MBR_SequenceOfOctetString_1,
	1,	/* Single element */
	&asn_SPC_SequenceOfOctetString_specs_1	/* Additional specs */
};

