/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER`
 */

#include "SymmetricEncryptionKey.h"

static int
memb_aes128Ccm_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_aes128Ccm_constr_2 GCC_NOTUSED = {
	{ 0, 0 },
	16	/* (SIZE(16..16)) */};
static asn_oer_constraints_t asn_OER_type_SymmetricEncryptionKey_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_SymmetricEncryptionKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SymmetricEncryptionKey, choice.aes128Ccm),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_aes128Ccm_constraint_1,
		&asn_OER_memb_aes128Ccm_constr_2,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aes128Ccm"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SymmetricEncryptionKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* aes128Ccm */
};
asn_CHOICE_specifics_t asn_SPC_SymmetricEncryptionKey_specs_1 = {
	sizeof(struct SymmetricEncryptionKey),
	offsetof(struct SymmetricEncryptionKey, _asn_ctx),
	offsetof(struct SymmetricEncryptionKey, present),
	sizeof(((struct SymmetricEncryptionKey *)0)->present),
	asn_MAP_SymmetricEncryptionKey_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SymmetricEncryptionKey = {
	"SymmetricEncryptionKey",
	"SymmetricEncryptionKey",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_oer,
	CHOICE_encode_oer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_OER_type_SymmetricEncryptionKey_constr_1,
	0,	/* No PER visible constraints */
	asn_MBR_SymmetricEncryptionKey_1,
	1,	/* Elements count */
	&asn_SPC_SymmetricEncryptionKey_specs_1	/* Additional specs */
};

