/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "1609dot2-schema.asn"
 * 	`asn1c -gen-OER`
 */

#include "ToBeSignedCertificate.h"

static asn_oer_constraints_t asn_OER_type_ToBeSignedCertificate_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_ToBeSignedCertificate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCertificate, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CertificateId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCertificate, cracaId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashedId3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cracaId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCertificate, crlSeries),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CrlSeries,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"crlSeries"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCertificate, validityPeriod),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ValidityPeriod,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"validityPeriod"
		},
	{ ATF_POINTER, 7, offsetof(struct ToBeSignedCertificate, region),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeographicRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"region"
		},
	{ ATF_POINTER, 6, offsetof(struct ToBeSignedCertificate, assuranceLevel),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectAssurance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"assuranceLevel"
		},
	{ ATF_POINTER, 5, offsetof(struct ToBeSignedCertificate, appPermissions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfPsidSsp,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"appPermissions"
		},
	{ ATF_POINTER, 4, offsetof(struct ToBeSignedCertificate, certIssuePermissions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfPsidGroupPermissions,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certIssuePermissions"
		},
	{ ATF_POINTER, 3, offsetof(struct ToBeSignedCertificate, certRequestPermissions),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfPsidGroupPermissions,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certRequestPermissions"
		},
	{ ATF_POINTER, 2, offsetof(struct ToBeSignedCertificate, canRequestRollover),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"canRequestRollover"
		},
	{ ATF_POINTER, 1, offsetof(struct ToBeSignedCertificate, encryptionKey),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PublicEncryptionKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptionKey"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCertificate, verifyKeyIndicator),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_VerificationKeyIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"verifyKeyIndicator"
		},
};
static const int asn_MAP_ToBeSignedCertificate_oms_1[] = { 4, 5, 6, 7, 8, 9, 10 };
static const ber_tlv_tag_t asn_DEF_ToBeSignedCertificate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ToBeSignedCertificate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cracaId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* crlSeries */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* validityPeriod */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* region */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* assuranceLevel */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* appPermissions */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* certIssuePermissions */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* certRequestPermissions */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* canRequestRollover */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* encryptionKey */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* verifyKeyIndicator */
};
asn_SEQUENCE_specifics_t asn_SPC_ToBeSignedCertificate_specs_1 = {
	sizeof(struct ToBeSignedCertificate),
	offsetof(struct ToBeSignedCertificate, _asn_ctx),
	asn_MAP_ToBeSignedCertificate_tag2el_1,
	12,	/* Count of tags in the map */
	asn_MAP_ToBeSignedCertificate_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	11,	/* Start extensions */
	13	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ToBeSignedCertificate = {
	"ToBeSignedCertificate",
	"ToBeSignedCertificate",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ToBeSignedCertificate_tags_1,
	sizeof(asn_DEF_ToBeSignedCertificate_tags_1)
		/sizeof(asn_DEF_ToBeSignedCertificate_tags_1[0]), /* 1 */
	asn_DEF_ToBeSignedCertificate_tags_1,	/* Same as above */
	sizeof(asn_DEF_ToBeSignedCertificate_tags_1)
		/sizeof(asn_DEF_ToBeSignedCertificate_tags_1[0]), /* 1 */
	&asn_OER_type_ToBeSignedCertificate_constr_1,
	0,	/* No PER visible constraints */
	asn_MBR_ToBeSignedCertificate_1,
	12,	/* Elements count */
	&asn_SPC_ToBeSignedCertificate_specs_1	/* Additional specs */
};

