/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "AdvisoryDetails.h"

static int
memb_advisoryMessage_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 1400)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_advisoryMessage_constr_7 GCC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..1400)) */};
static asn_per_constraints_t asn_PER_memb_advisoryMessage_constr_7 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  0,  1400 }	/* (SIZE(0..1400)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AdvisoryDetails_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AdvisoryDetails, asdmID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"asdmID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdvisoryDetails, asdmType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdvisoryBroadcastType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"asdmType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdvisoryDetails, distType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DistributionType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"distType"
		},
	{ ATF_POINTER, 2, offsetof(struct AdvisoryDetails, startTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"startTime"
		},
	{ ATF_POINTER, 1, offsetof(struct AdvisoryDetails, stopTime),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"stopTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdvisoryDetails, advisoryMessage),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_advisoryMessage_constraint_1,
		&asn_OER_memb_advisoryMessage_constr_7,
		&asn_PER_memb_advisoryMessage_constr_7,
		0,
		"advisoryMessage"
		},
};
static const int asn_MAP_AdvisoryDetails_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_AdvisoryDetails_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AdvisoryDetails_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* asdmID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* asdmType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* distType */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* startTime */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* stopTime */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* advisoryMessage */
};
asn_SEQUENCE_specifics_t asn_SPC_AdvisoryDetails_specs_1 = {
	sizeof(struct AdvisoryDetails),
	offsetof(struct AdvisoryDetails, _asn_ctx),
	asn_MAP_AdvisoryDetails_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_AdvisoryDetails_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AdvisoryDetails = {
	"AdvisoryDetails",
	"AdvisoryDetails",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AdvisoryDetails_tags_1,
	sizeof(asn_DEF_AdvisoryDetails_tags_1)
		/sizeof(asn_DEF_AdvisoryDetails_tags_1[0]), /* 1 */
	asn_DEF_AdvisoryDetails_tags_1,	/* Same as above */
	sizeof(asn_DEF_AdvisoryDetails_tags_1)
		/sizeof(asn_DEF_AdvisoryDetails_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_AdvisoryDetails_1,
	6,	/* Elements count */
	&asn_SPC_AdvisoryDetails_specs_1	/* Additional specs */
};

