/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "BroadcastInstructions.h"

asn_TYPE_member_t asn_MBR_BroadcastInstructions_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastInstructions, biType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdvisoryBroadcastType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"biType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastInstructions, biPriority),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Priority,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"biPriority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastInstructions, biDeliveryStart),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"biDeliveryStart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastInstructions, biDeliveryStop),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"biDeliveryStop"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastInstructions, biSignature),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"biSignature"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BroadcastInstructions, biEncryption),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"biEncryption"
		},
	{ ATF_POINTER, 1, offsetof(struct BroadcastInstructions, dsrcInst),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DsrcInstructions,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"dsrcInst"
		},
};
static const int asn_MAP_BroadcastInstructions_oms_1[] = { 6 };
static const ber_tlv_tag_t asn_DEF_BroadcastInstructions_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BroadcastInstructions_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* biType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* biPriority */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* biDeliveryStart */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* biDeliveryStop */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* biSignature */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* biEncryption */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* dsrcInst */
};
asn_SEQUENCE_specifics_t asn_SPC_BroadcastInstructions_specs_1 = {
	sizeof(struct BroadcastInstructions),
	offsetof(struct BroadcastInstructions, _asn_ctx),
	asn_MAP_BroadcastInstructions_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_BroadcastInstructions_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	6,	/* Start extensions */
	8	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BroadcastInstructions = {
	"BroadcastInstructions",
	"BroadcastInstructions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BroadcastInstructions_tags_1,
	sizeof(asn_DEF_BroadcastInstructions_tags_1)
		/sizeof(asn_DEF_BroadcastInstructions_tags_1[0]), /* 1 */
	asn_DEF_BroadcastInstructions_tags_1,	/* Same as above */
	sizeof(asn_DEF_BroadcastInstructions_tags_1)
		/sizeof(asn_DEF_BroadcastInstructions_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_BroadcastInstructions_1,
	7,	/* Elements count */
	&asn_SPC_BroadcastInstructions_specs_1	/* Additional specs */
};

