/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "DataSubscriptionRequest.h"

static asn_oer_constraints_t asn_OER_type_type_constr_6 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_type_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_type_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct type, choice.vsmType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VsmType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"vsmType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct type, choice.isdType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IsdType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"isdType"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_type_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vsmType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* isdType */
};
static asn_CHOICE_specifics_t asn_SPC_type_specs_6 = {
	sizeof(struct type),
	offsetof(struct type, _asn_ctx),
	offsetof(struct type, present),
	sizeof(((struct type *)0)->present),
	asn_MAP_type_tag2el_6,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_type_6 = {
	"type",
	"type",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_oer,
	CHOICE_encode_oer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_OER_type_type_constr_6,
	&asn_PER_type_type_constr_6,
	asn_MBR_type_6,
	2,	/* Elements count */
	&asn_SPC_type_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DataSubscriptionRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DataSubscriptionRequest, dialogID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiDialogID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"dialogID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataSubscriptionRequest, seqID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiSequenceID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"seqID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataSubscriptionRequest, groupID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GroupID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"groupID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataSubscriptionRequest, requestID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"requestID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataSubscriptionRequest, type),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_type_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataSubscriptionRequest, endTime),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DFullTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"endTime"
		},
	{ ATF_POINTER, 1, offsetof(struct DataSubscriptionRequest, serviceRegion),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeoRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"serviceRegion"
		},
};
static const int asn_MAP_DataSubscriptionRequest_oms_1[] = { 6 };
static const ber_tlv_tag_t asn_DEF_DataSubscriptionRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DataSubscriptionRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dialogID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* seqID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* groupID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* requestID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* endTime */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* serviceRegion */
};
static asn_SEQUENCE_specifics_t asn_SPC_DataSubscriptionRequest_specs_1 = {
	sizeof(struct DataSubscriptionRequest),
	offsetof(struct DataSubscriptionRequest, _asn_ctx),
	asn_MAP_DataSubscriptionRequest_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_DataSubscriptionRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DataSubscriptionRequest = {
	"DataSubscriptionRequest",
	"DataSubscriptionRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DataSubscriptionRequest_tags_1,
	sizeof(asn_DEF_DataSubscriptionRequest_tags_1)
		/sizeof(asn_DEF_DataSubscriptionRequest_tags_1[0]), /* 1 */
	asn_DEF_DataSubscriptionRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_DataSubscriptionRequest_tags_1)
		/sizeof(asn_DEF_DataSubscriptionRequest_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_DataSubscriptionRequest_1,
	7,	/* Elements count */
	&asn_SPC_DataSubscriptionRequest_specs_1	/* Additional specs */
};

