/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "Environmental.h"

asn_TYPE_member_t asn_MBR_Environmental_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Environmental, fuelCon),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FuelConsumption,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"fuelCon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Environmental, emiss),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Emissions,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"emiss"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Environmental, fuelEcon),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FuelEconomy,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"fuelEcon"
		},
};
static const ber_tlv_tag_t asn_DEF_Environmental_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Environmental_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fuelCon */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* emiss */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* fuelEcon */
};
asn_SEQUENCE_specifics_t asn_SPC_Environmental_specs_1 = {
	sizeof(struct Environmental),
	offsetof(struct Environmental, _asn_ctx),
	asn_MAP_Environmental_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Environmental = {
	"Environmental",
	"Environmental",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_oer,
	SEQUENCE_encode_oer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Environmental_tags_1,
	sizeof(asn_DEF_Environmental_tags_1)
		/sizeof(asn_DEF_Environmental_tags_1[0]), /* 1 */
	asn_DEF_Environmental_tags_1,	/* Same as above */
	sizeof(asn_DEF_Environmental_tags_1)
		/sizeof(asn_DEF_Environmental_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_Environmental_1,
	3,	/* Elements count */
	&asn_SPC_Environmental_specs_1	/* Additional specs */
};

