/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#ifndef	_HashAlgorithm_H_
#define	_HashAlgorithm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HashAlgorithm {
	HashAlgorithm_sha256	= 0
	/*
	 * Enumeration is extensible
	 */
} e_HashAlgorithm;

/* HashAlgorithm */
typedef long	 HashAlgorithm_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HashAlgorithm_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HashAlgorithm;
extern asn_INTEGER_specifics_t asn_SPC_HashAlgorithm_specs_1;
asn_struct_free_f HashAlgorithm_free;
asn_struct_print_f HashAlgorithm_print;
asn_constr_check_f HashAlgorithm_constraint;
ber_type_decoder_f HashAlgorithm_decode_ber;
der_type_encoder_f HashAlgorithm_encode_der;
xer_type_decoder_f HashAlgorithm_decode_xer;
xer_type_encoder_f HashAlgorithm_encode_xer;
oer_type_decoder_f HashAlgorithm_decode_oer;
oer_type_encoder_f HashAlgorithm_encode_oer;
per_type_decoder_f HashAlgorithm_decode_uper;
per_type_encoder_f HashAlgorithm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HashAlgorithm_H_ */
#include <asn_internal.h>
