/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2BaseTypes"
 * 	found in "1609dot2-base-types.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "IdentifiedRegion.h"

static asn_oer_constraints_t asn_OER_type_IdentifiedRegion_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_IdentifiedRegion_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_IdentifiedRegion_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IdentifiedRegion, choice.countryOnly),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CountryOnly,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"countryOnly"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentifiedRegion, choice.countryAndRegions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CountryAndRegions,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"countryAndRegions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentifiedRegion, choice.countryAndSubregions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CountryAndSubregions,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"countryAndSubregions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_IdentifiedRegion_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* countryOnly */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* countryAndRegions */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* countryAndSubregions */
};
asn_CHOICE_specifics_t asn_SPC_IdentifiedRegion_specs_1 = {
	sizeof(struct IdentifiedRegion),
	offsetof(struct IdentifiedRegion, _asn_ctx),
	offsetof(struct IdentifiedRegion, present),
	sizeof(((struct IdentifiedRegion *)0)->present),
	asn_MAP_IdentifiedRegion_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_IdentifiedRegion = {
	"IdentifiedRegion",
	"IdentifiedRegion",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_oer,
	CHOICE_encode_oer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_OER_type_IdentifiedRegion_constr_1,
	&asn_PER_type_IdentifiedRegion_constr_1,
	asn_MBR_IdentifiedRegion_1,
	3,	/* Elements count */
	&asn_SPC_IdentifiedRegion_specs_1	/* Additional specs */
};

