/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE1609dot2"
 * 	found in "1609dot2-schema.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "RecipientInfo.h"

static asn_oer_constraints_t asn_OER_type_RecipientInfo_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_RecipientInfo_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RecipientInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientInfo, choice.pskRecipInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PreSharedKeyRecipientInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"pskRecipInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientInfo, choice.symmRecipInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SymmRecipientInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"symmRecipInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientInfo, choice.certRecipInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PKRecipientInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"certRecipInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientInfo, choice.signedDataRecipInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PKRecipientInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"signedDataRecipInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RecipientInfo, choice.rekRecipInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PKRecipientInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No OER visible constraints */
		0,	/* No PER visible constraints */
		0,
		"rekRecipInfo"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RecipientInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pskRecipInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* symmRecipInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* certRecipInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* signedDataRecipInfo */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* rekRecipInfo */
};
asn_CHOICE_specifics_t asn_SPC_RecipientInfo_specs_1 = {
	sizeof(struct RecipientInfo),
	offsetof(struct RecipientInfo, _asn_ctx),
	offsetof(struct RecipientInfo, present),
	sizeof(((struct RecipientInfo *)0)->present),
	asn_MAP_RecipientInfo_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RecipientInfo = {
	"RecipientInfo",
	"RecipientInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_oer,
	CHOICE_encode_oer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_OER_type_RecipientInfo_constr_1,
	&asn_PER_type_RecipientInfo_constr_1,
	asn_MBR_RecipientInfo_1,
	5,	/* Elements count */
	&asn_SPC_RecipientInfo_specs_1	/* Additional specs */
};

