/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#include "SemiDialogID.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_SemiDialogID_constr_1 GCC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SemiDialogID_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_SemiDialogID_value2enum_1[] = {
	{ 154,	10,	"vehSitData" },
	{ 155,	16,	"dataSubscription" },
	{ 156,	13,	"advSitDataDep" },
	{ 157,	13,	"advSitDatDist" },
	{ 158,	9,	"reserved1" },
	{ 159,	9,	"reserved2" },
	{ 160,	6,	"objReg" },
	{ 161,	7,	"objDisc" },
	{ 162,	22,	"intersectionSitDataDep" },
	{ 163,	24,	"intersectionSitDataQuery" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_SemiDialogID_enum2value_1[] = {
	3,	/* advSitDatDist(157) */
	2,	/* advSitDataDep(156) */
	1,	/* dataSubscription(155) */
	8,	/* intersectionSitDataDep(162) */
	9,	/* intersectionSitDataQuery(163) */
	7,	/* objDisc(161) */
	6,	/* objReg(160) */
	4,	/* reserved1(158) */
	5,	/* reserved2(159) */
	0	/* vehSitData(154) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_SemiDialogID_specs_1 = {
	asn_MAP_SemiDialogID_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SemiDialogID_enum2value_1,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	11,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SemiDialogID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SemiDialogID = {
	"SemiDialogID",
	"SemiDialogID",
	NativeEnumerated_free,
	NativeEnumerated_print,
	NativeEnumerated_constraint,
	NativeEnumerated_decode_ber,
	NativeEnumerated_encode_der,
	NativeEnumerated_decode_xer,
	NativeEnumerated_encode_xer,
	NativeEnumerated_decode_oer,
	NativeEnumerated_encode_oer,
	NativeEnumerated_decode_uper,
	NativeEnumerated_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SemiDialogID_tags_1,
	sizeof(asn_DEF_SemiDialogID_tags_1)
		/sizeof(asn_DEF_SemiDialogID_tags_1[0]), /* 1 */
	asn_DEF_SemiDialogID_tags_1,	/* Same as above */
	sizeof(asn_DEF_SemiDialogID_tags_1)
		/sizeof(asn_DEF_SemiDialogID_tags_1[0]), /* 1 */
	&asn_OER_type_SemiDialogID_constr_1,
	&asn_PER_type_SemiDialogID_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SemiDialogID_specs_1	/* Additional specs */
};

