/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#ifndef	_ServiceRecord_H_
#define	_ServiceRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceProviderID.h"
#include "TimeToLive.h"
#include "GeoRegion.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "SEMI_Psid.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConnectionPoint;

/* ServiceRecord */
typedef struct ServiceRecord {
	struct connectionPoints {
		A_SEQUENCE_OF(struct ConnectionPoint) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} connectionPoints;
	ServiceProviderID_t	 svcProvider;
	struct svcPSIDs {
		A_SEQUENCE_OF(SEMI_Psid_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} svcPSIDs;
	TimeToLive_t	*timeToLive	/* OPTIONAL */;
	GeoRegion_t	 serviceRegion;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_ServiceRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_ServiceRecord_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConnectionPoint.h"

#endif	/* _ServiceRecord_H_ */
#include <asn_internal.h>
