/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#ifndef	_ServiceResponse_H_
#define	_ServiceResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SemiDialogID.h"
#include "SemiSequenceID.h"
#include "GroupID.h"
#include "TemporaryID.h"
#include "DDateTime.h"
#include "Sha256Hash.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeoRegion;

/* ServiceResponse */
typedef struct ServiceResponse {
	SemiDialogID_t	 dialogID;
	SemiSequenceID_t	 seqID;
	GroupID_t	 groupID;
	TemporaryID_t	 requestID;
	DDateTime_t	 expiration;
	struct GeoRegion	*serviceRegion	/* OPTIONAL */;
	Sha256Hash_t	 hash;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeoRegion.h"

#endif	/* _ServiceResponse_H_ */
#include <asn_internal.h>
