/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SEMI"
 * 	found in "SEMI_v2.3.0_070616.asn"
 * 	`asn1c -gen-OER -gen-PER`
 */

#ifndef	_VehicleSituationStatus_H_
#define	_VehicleSituationStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExteriorLights.h"
#include "ThrottlePosition.h"
#include "TirePressure.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSituationStatus */
typedef struct VehicleSituationStatus {
	ExteriorLights_t	 lights;
	ThrottlePosition_t	*throttlePos	/* OPTIONAL */;
	struct tirePressure {
		TirePressure_t	 leftFront;
		TirePressure_t	 leftRear;
		TirePressure_t	 rightFront;
		TirePressure_t	 rightRear;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tirePressure;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSituationStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSituationStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSituationStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSituationStatus_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSituationStatus_H_ */
#include <asn_internal.h>
