name: asn1-codec

on: [pull_request, push]
    # Trigger this workflow on code pushes and pull requests

jobs:
  asn1-codec:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20230126
      env:
        working-directory: /asn1_codec
      options: "--user root"
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        # Checkout the code from the repository

      - name: Install necessary dependencies
        run: |
          apt update
          apt-get -y install sudo wget curl gnupg lsb-release gcovr unzip gcc-multilib libasan*
          sudo apt-get -y install software-properties-common
          sudo apt-get -y install libcurl4-openssl-dev
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          sudo apt-get -y update
          sudo apt-get -y install docker-ce
        working-directory: ${{ env.working-directory }}
        
      - name: Install g++ and related dependencies
        run: |
          sudo apt-get -y install build-essential
          sudo apt -y install cmake g++ libprotobuf-dev protobuf-compiler
          sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
          export CXX="g++"
          sudo apt install -y gcc-12 g++-12
          sudo apt -y install libpng-dev libgraphicsmagick1-dev libcairo2-dev
        working-directory: ${{ env.working-directory }}

      - name: Install librdkafka
        run: |
          sudo apt-get -y update && sudo apt-get -y upgrade
          sudo apt-get -y install automake flex bison libasio-dev
          sudo apt-get -y install build-essential
          sudo apt -y install cmake g++ libprotobuf-dev protobuf-compiler
          sudo apt-get install autotools-dev
          sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
          git clone --depth 1 https://github.com/confluentinc/librdkafka.git librdkafka
          cd librdkafka
          cmake -H. -B_cmake_build
          cmake --build _cmake_build
          cmake --build _cmake_build --target install
        working-directory: ${{ env.working-directory }}

      - name: Install pugixml
        run: |
          git clone https://github.com/zeux/pugixml.git
          cd ./pugixml && mkdir -p build && cd build && cmake .. && make && make install
        working-directory: ${{ env.working-directory }}

      - name: Extract implementation and header files
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib
          cd ./asn1c_combined && bash doIt.sh
        working-directory: ${{ env.working-directory }}

      - name: Export environment variables
        run: |
          echo "export LD_LIBRARY_PATH=/usr/local/lib" >> ~/.profile
          echo "export LD_LIBRARY_PATH=/usr/local/lib" >> ~/.bashrc
          echo "export CC=gcc" >> ~/.profile
          echo "export CC=gcc" >> ~/.bashrc
        working-directory: ${{ env.working-directory }}

      - name: Build and Generate test coverage
        run: |
          sudo su - root
          sudo chmod o+w /root
          sudo chmod 755 -R /__w/asn1_codec/asn1_codec/
          ./build.sh
          mkdir -p coverage
          gcovr \
            --root $GITHUB_WORKSPACE \
            --object-directory $GITHUB_WORKSPACE/build \
            --xml coverage/coverage.xml \
            --exclude '.*pugixml.*' \
            --exclude '.*librdkafka.*'
        working-directory: ${{ env.working-directory }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v7
        with:
          name: asn1-codec
          path: /__w/asn1-codec/asn1-codec/coverage/
        # Archive code coverage results for later reference

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name:  SonarScanner
        if: github.event.pull_request.base.repo.owner.login == 'usdot-jpo-ode'
        uses: usdot-fhwa-stol/actions/sonar-scanner@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          working-dir: $GITHUB_WORKSPACE   
